### ISSUE TITLE
Misplaced ` in readme

### ISSUE THREAD

**Issue by acoulon99** [davidtimmons/metalsmith-preview#1]
It seems that there are some misplaced ` in the Readme:

![image](https://user-images.githubusercontent.com/9921114/33907125-b1fd9aee-df49-11e7-908e-0118c5e80687.png)

**Comment by acoulon99** [comment]
first!

**Comment by davidtimmons** [comment]
Thanks for letting me know, @acoulon99! I just pushed a fixed version of that table: 464a63dc056ea66c331d622d399f5dc23bbe00ad.
