### ISSUE TITLE
How not to escape special characters like apostrophes?

### ISSUE THREAD

**Issue by matthiasguentert** [davidtimmons/metalsmith-preview#2]
Hello David

I am using the latest version of your plugin (`"metalsmith-preview": "^1.0.6"`). This is what my configuration looks like:
```
var preview = require('metalsmith-preview');
var preview_options = {
    "pattern": "**/posts/*.html",
    "strip": "",           // Do not strip off anything, leave html tags in place
    "marker": {
        "start": "{{ previewStart }}",
        "end": "{{ previewEnd }}"
    }
}

// ...

metalsmith(__dirname)
    .metadata(metadata_config)
    .source('../source')
    .destination('../build')
    .clean(true)
    .use(metallic())
    .use(markdown())
    .use(preview(preview_options))
    // ...
   .build(errorHandler);
```

One of my markdown files has the following content...
`{{ previewStart }} ... but doesn't take ... {{ previewEnd }}`

...which results in: 
`"preview": "... but doesn&#39;t take ... ...",`

So the plugin seems to escape the apostrophe. It doesn't make a change if I leave `strip:` to the default values. How can I make the plugin stop doing this?

**Comment by matthiasguentert** [comment]
Doo, it seems that `metalsmith-markdown` is the culprit, and not this plugin. Sorry for the noise...

**Comment by davidtimmons** [comment]
No worries! I hope this plugin is useful for you.
